version: '3.8'

services:
  payments-db:
    image: postgres:15
    container_name: payments-db
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data
    networks:
      - payments-network

  payments-service:
    build: .
    container_name: payments-service
    environment:
      - PORT=3004
      - DB_HOST=payments-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=payments_db
      - JWT_SECRET=your-secret-key
      - RABBITMQ_URL=amqp://admin:admin@host.docker.internal:5672
      - RABBITMQ_MANAGEMENT_URL=http://host.docker.internal:15672
      - STRIPE_SECRET_KEY=
    ports:
      - "3004:3004"
    depends_on:
      - payments-db
    networks:
      - payments-network

volumes:
  payments_db_data:

networks:
  payments-network:
    driver: bridge